### ISSUE TITLE
Any chance of an update to this?

### ISSUE THREAD

**Issue by nicholasgriffintn** [NAStools/homeassistant#1]
Hey,

This is pretty awesome, running home assistant on a NAS seems obvious to me as it's there anyway and I'd love to do it. The only problem is that this is quite an outdated version, is there any chance of you updating this project again or do you not use it anymore?

If not, how do you update this? I have no clue about ReadyNAS apps.

**Comment by eclaassens** [comment]
I second that!

Yesterday I tried hass.io on my RPi1. Installing was a breeze but it was really slow. Today I found this fork!  I looked into manually updating but it seems that the project has made a drastic change in technical components...I cannot recognise the structure anymore :(

**Comment by grtessman** [comment]
+2 - an update for ReadyNAS would be great!

**Comment by MJP-76** [comment]
Me 3. Really nice, but an update would be great

**Comment by seetendra** [comment]
Me 4

**Comment by seetendra** [comment]
ME 5

**Comment by shafy14** [comment]
waiting, anyone got a chance on installing in a different way?

**Comment by eclaassens** [comment]
I switched to dockers years ago! That is sooo much easier (also for updating). 
Using docker-compose files to setup to make it really easy.

```
version: '2'

services:
    dbhass:
        container_name: dbhass
        image: postgres:9.6
        volumes:
            - /data/Documents/docker-files/postgresql_hass:/var/lib/postgresql/data
            - /etc/localtime:/etc/localtime:ro
        environment:
            - POSTGRES_DB=hass
            - POSTGRES_USER=hass
            - POSTGRES_PASSWORD=HassSecret
        network_mode: host
        ports:
            - '5432:5432'
        restart: on-failure
    home-assistant:
        container_name: home-assistant
        image: homeassistant/home-assistant:latest
        depends_on:
            - dbhass
        volumes:
            - /data/Documents/docker-files/ha_config:/config
            - /etc/localtime:/etc/localtime:ro
        network_mode: host
        ports:
            - '8123:8123'
        restart: on-failure
```
